"""Gitea API client for posting review comments."""

import requests
from config import Config


class GiteaClient:
    """Client for posting review comments to Gitea PRs."""

    def __init__(self, config: Config, token: str):
        self.config = config
        self.token = token
        self.headers = {
            "Authorization": f"token {token}",
            "Content-Type": "application/json",
        }

    def _get_pr_head_sha(self, repo_name: str, pr_number: int) -> str:
        """Get the head commit SHA for a PR."""
        url = f"{self.config.gitea_url}/api/v1/repos/{repo_name}/pulls/{pr_number}"
        response = requests.get(url, headers=self.headers)
        response.raise_for_status()
        return response.json().get("head", {}).get("sha", "")

    def post_review(
        self,
        repo_name: str,
        pr_number: int,
        comments: list,
        summaries: list
    ) -> None:
        """Post inline comments and summary to a PR."""
        head_sha = self._get_pr_head_sha(repo_name, pr_number)
        if not head_sha:
            print("Warning: Could not get head SHA, skipping inline comments")
            return

        icons = self.config.severity_icons or {
            "critical": "🔴", "error": "🟠", "warning": "🟡", "info": "🔵"
        }

        # Post inline comments as a review
        if comments:
            formatted = []
            severity_counts = {"critical": 0, "error": 0, "warning": 0, "info": 0}

            for c in comments:
                sev = c.get("severity", "info")
                severity_counts[sev] = severity_counts.get(sev, 0) + 1
                icon = icons.get(sev, "💬")
                formatted.append({
                    "body": f"{icon} **{sev.upper()}**: {c.get('message', '')}",
                    "path": c.get("file", ""),
                    "new_position": c.get("line", 1),
                })

            # Build review body
            body = f"{self.config.bot_emoji} **{self.config.bot_name} - Inline Comments**\n\n"
            body += f"Found **{len(comments)}** item(s):\n"
            for sev, icon in icons.items():
                if severity_counts.get(sev, 0) > 0:
                    body += f"- {icon} {sev.title()}: {severity_counts[sev]}\n"

            url = f"{self.config.gitea_url}/api/v1/repos/{repo_name}/pulls/{pr_number}/reviews"
            payload = {"body": body, "commit_id": head_sha, "comments": formatted}

            try:
                response = requests.post(url, headers=self.headers, json=payload)
                if response.status_code in (200, 201):
                    print(f"Posted review with {len(comments)} inline comments")
                else:
                    print(f"Failed to post review: {response.status_code} {response.text}")
            except Exception as e:
                print(f"Error posting review: {e}")

        # Post summary comment
        if summaries:
            combined = {
                "overview": " ".join(s.get("overview", "") for s in summaries),
                "strengths": [],
                "issues": [],
                "suggestions": [],
            }
            for s in summaries:
                combined["strengths"].extend(s.get("strengths", []))
                combined["issues"].extend(s.get("issues", []))
                combined["suggestions"].extend(s.get("suggestions", []))

            body = f"## {self.config.bot_emoji} {self.config.bot_name} Summary\n\n"
            if combined["overview"]:
                body += f"**Overview:** {combined['overview']}\n\n"

            if combined["strengths"]:
                body += "### ✅ Strengths\n"
                for s in combined["strengths"][:5]:
                    body += f"- {s}\n"
                body += "\n"

            if combined["issues"]:
                body += "### ⚠️ Issues\n"
                for i in combined["issues"][:10]:
                    body += f"- {i}\n"
                body += "\n"

            if combined["suggestions"]:
                body += "### 💡 Suggestions\n"
                for s in combined["suggestions"][:5]:
                    body += f"- {s}\n"
                body += "\n"

            body += "---\n*Generated by AI. Please review and use your judgment.*"

            url = f"{self.config.gitea_url}/api/v1/repos/{repo_name}/issues/{pr_number}/comments"
            try:
                response = requests.post(url, headers=self.headers, json={"body": body})
                if response.status_code in (200, 201):
                    print("Posted summary comment")
                else:
                    print(f"Failed to post summary: {response.status_code}")
            except Exception as e:
                print(f"Error posting summary: {e}")
